apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: aplicacao-deployment
spec:
  replicas: 10
  template:
    metadata:
      labels:
       name: aplicacao-nginx
    spec:
      containers:
        - name: container-aplicacao-nginx
          image: concretecristiantrucco/bbmtalk  
          ports:
            - containerPort: 80
