---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: aplicacao-feature-express
spec:
  replicas: 2 
  template:
    metadata:
      labels:
       name: aplicacao-feature-express
    spec:
      containers:
        - name: container-feature-express
          image: concretecristiantrucco/feature-express
          ports:
            - containerPort: 3000
---

apiVersion: v1
kind: Service
metadata:
  name: servico-aplicacao-feature-express
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30300

  selector:
    name: aplicacao-feature-express

---
### Deve ter controlador ingress implantado no cluster

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: aplicacao-feature-express
spec:
 rules:
   - host: aplicacao-feature-express
     http:
       paths:
         - path: /
           backend:
             serviceName: servico-aplicacao-feature-express
             servicePort: 3000



